[default]
template_dir = "templates/"
secret_key = "OIXQA1y4NNCFHHy5XuHCZiyzVE/Np6z5PACE+wyTVhw="

[default.databases.sea_orm]
# Mysql
# make sure to enable "sqlx-mysql" feature in Cargo.toml, i.e default = ["sqlx-mysql"]
url = "sqlite://static/database/db.sqlite?mode=rwc"
