[default]
template_dir = "templates/"
secret_key = "OIXQA1y4NNCFHHy5XuHCZiyzVE/Np6z5PACE+wyTVhw="

[default.databases]
mxf = { url = "mysql://root:root_mxf_passwd@24fcd635ab85.c.methodot.com:30444/mxf" }
